steps:
- name: 'gcr.io/cloud-builders/mvn'
  args: ['install']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/javabuild-253405/dockerfilejava', '.']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['app', 'deploy', 'app.yaml', '--image-url', 'gcr.io/javabuild-253405/dockerfilejava']
  
images: ['gcr.io/javabuild-253405/dockerfilejava']
