steps:
- name: 'gcr.io/cloud-builders/mvn'
  args: ['install']
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/dockernew-253806/dockerfilejava', '.']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['app', 'create', '--region', 'us-central']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['app', 'deploy', 'app.yaml', '--image-url', 'gcr.io/dockernew-253806/dockerfilejava']
  
images: ['gcr.io/dockernew-253806/dockerfilejava']
